name: tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Create secret
        shell: bash
        run: |
          echo ${{ secrets.API_KEY }}$ > .secret.txt
          pwd
          ls -a
      - name: Run tests with Maven
        run: |
          mvn -B test --file pom.xml
      - name: Print report
        run: |
          ls ./target/surefire-reports
          cat ./target/surefire-reports/OMDBApiTest.txt
